/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { GenericERC20 } from "./GenericERC20";

export { GenericERC20__factory } from "./factories/GenericERC20__factory";
